baseURL = 'http://sunnote.xyz'

languageCode = "zh-tw"

title = 'Sun è¨˜äº‹'
theme = 'Mainroad'

paginate = "5" # Number of posts per page
disqusShortname = "sun"

googleAnalytics = "G-MWPM4C5TJS"

[Author] # Used in authorbox
  name = "Alvin"
  bio = "ä¸æ˜¯ä¸€å€‹å¾ˆåŠªåŠ›çš„äººï¼Œç”Ÿæ´»å°±æ˜¯åœ¨è€å»¢ä¸­é †ä¾¿è¿½æ±‚é»æˆå°±æ„Ÿã€‚"
  avatar = "img/avatar.jpg"
[Params]
  googleCustomSearch = "51cfcdef3e098403d" # Google Custom Search Engine ID
  description = "Life is tough, but so are you." # Site description. Used in meta description
  copyright = "sunnote" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information "author", , "translations"

  dateformat = "January 2, 2006" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300&display=swap" # Load Google Fonts
  # customCSS = ["css/dark.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files
  page_view_conter = true
  likerID = "sunnote"


  # DEPRECATED PARAMS
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor

[Params.logo]
  image = "" # Logo image. Path relative to "static"
  title = "Sun Notes" # Logo title, otherwise will use site title
  subtitle = "Life is tough, but so are you." # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = [ "recent", "categories", "search", "taglist", "flag", "announcement"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
   github = "zhongyousun"
# Custom social links

# i18n
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = true
# ä¸­æ–‡
[languages.zh-tw]
    languageName = "ğŸ‡¹ğŸ‡¼"
    contentDir = "content/zh-tw"
    weight = 1
# è‹±æ–‡ç‰ˆæœ¬
[languages.en]
    title = "Sun Notes"
    languageName = "us"
    contentDir = "content/en-us"
    weight = 2
    [languages.en.Author]
      name = "Alvin"
      bio = "Life is about pursuing a sense of accomplishment while messing around."
      avatar = "img/avatar.jpg"
    [languages.en.Params.sidebar]
      home = "right" # Configure layout for home page
      list = "right"  # Configure layout for list pages
      single = true # Configure layout for single pages
      #    Enable widgets in given order
      widgets = ["recent", "categories", "search", "taglist", "flag", "announcement"]
    

[[menu.main]]
  name = "En"
  url = "../"
  weight = 7

[[languages.en.menu.main]]
  pre = "<i class='fas fa-house'></i>"
  # ğŸ“ƒğŸ”ğŸ—„ï¸ğŸŒ
  name = "About"
  url = "/about"
  weight = 2
[[languages.en.menu.main]]
  pre = "<i class='fas fa-magnifying-glass'></i>"
  name = "Site Search"
  weight = 3
  identifier = "search"
  url = "/search"
[[languages.en.menu.main]]
  pre = "<i class='fas fa-box-archive'></i>"
  name = "Archives"
  identifier = "Archives"
  weight = 4
  url = "/archives"
[[languages.en.menu.main]]
  pre = "<i class='fas fa-plane'></i>"
  identifier = "travel"
  name = "Life"
  weight = 5
  [[languages.en.menu.main]]
    name = "Philippines"
    url = "/tags/philippines/"
    parent = "travel"
    weight = 1
  [[languages.en.menu.main]]
    name = "Cebu"
    url = "/tags/cebu/"
    parent = "travel"
    weight = 2
  [[languages.en.menu.main]]
    name = "Taiwan"
    url = "/tags/Taiwan/"
    parent = "travel"
    weight = 3
  
[[languages.en.menu.main]]
  pre = "<i class='fas fa-globe'></i>"
  identifier = "language"
  name = " "
  # url = "/zh-tw"
  weight = 6
  [[languages.en.menu.main]]
    name = "Zh"
    url = "/zh-tw"
    parent = "language"
    weight = 1
  [[languages.en.menu.main]]
    name = "EN"
    url = "/"
    parent = "language"
    weight = 1


[[languages.zh-tw.menu.main]]
  pre = "<i class='fas fa-house'></i>"
  name = "é—œæ–¼"
  url = "/zh-tw/about"
  weight = 2
[[languages.zh-tw.menu.main]]
  pre = "<i class='fas fa-magnifying-glass'></i>"
  name = "ç«™å…§æŸ¥è©¢"
  weight = 3
  identifier = "search"
  url = "/zh-tw/search"
[[languages.zh-tw.menu.main]]
  pre = "<i class='fas fa-box-archive'></i>"
  name = "æ–‡ç« æ­¸æª”"
  weight = 4
  url = "/zh-tw/archives"
[[languages.zh-tw.menu.main]]
  pre = "<i class='fas fa-plane'></i>"
  identifier = "travel"
  name = "ç”Ÿæ´»"
  weight = 5
  [[languages.zh-tw.menu.main]]
    name = "è²å¾‹è³“"
    url = "/zh-tw/tags/è²å¾‹è³“/"
    parent = "travel"
    weight = 1
  [[languages.zh-tw.menu.main]]
    name = "å®¿éœ§"
    url = "/zh-tw/tags/å®¿éœ§/"
    parent = "travel"
    weight = 2
  [[languages.zh-tw.menu.main]]
    name = "å°ç£"
    url = "/zh-tw/tags/å°ç£/"
    parent = "travel"
    weight = 3
[[languages.zh-tw.menu.main]]
  pre = "<i class='fas fa-globe'></i>"
  identifier = "language"
  name = " "
  # url = "/zh-tw"
  weight = 6
  [[languages.zh-tw.menu.main]]
    name = "Zh"
    url = "/zh-tw"
    parent = "language"
    weight = 1
  [[languages.zh-tw.menu.main]]
    name = "EN"
    url = "/"
    parent = "language"
    weight = 1



[permalinks]
  posts = '/:slug/'

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# [related]
#     treshold = 1
#     includeNewer = true
#     toLower = false

#     [[related.indices]]
#         name = "CurrentSection.Title"
#         weight = 75
#     [[related.indices]]
#         name = "Section.Title"
#         weight = 50
#     [[related.indices]]
#         name = "description"
#         weight = 25
[outputs]
  home = ["HTML","RSS","Algolia"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
[params.algolia]
  appId = "6CA8UYGMKF"
  indexName = "sunnote_en"
  searchOnlyKey = "0b6aa5d5a7d49848cea785697d9a99ba"
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"] 
  params = ["categories", "tags", "series"]
 
[outputFormats.Algolia]
  mediaType = "application/json"
  baseName = "algolia"
  isPlainText = true
